config/routes.rb
Conectup::Application.routes.draw do
 
  get "comments/index"
  get "comments/new"
  devise_for :users
  root :to => "users#show"
  
  resources :users do 
    resources :comments
  end

  resources :businesses do 
    resources :comments
  end

  resources :searches do
    resources :comments
  end

  resources :jobs do 
    resources :comments
  end

  resources :friendships do
    resources :comments
  end

  resources :comments

  

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  def index
    @businesses = Business.all
    @categories = Business.categories
    @by_employees = Business.by_employee_count.reverse
  end

  def show
    @business = Business.find(params[:id])
    @positions = Business.find(params[:id]).positions_list
    # if current_user != nil
    #   @job = current_user.jobs.select do |job|       binding.pry 
    #     if job.business.id == params[:id]
    #       job
    #     end
    #   end
    # end
  end


end

app/views/businesses/index.html.erb
<h1>All Businesses</h1>

<h2>By Category</h2>
<% @businesses.categories.each do |category, businesses| %>
	<h3> <%= category %> </h3>
	<% businesses.each do |business| %>
		<h4><%= link_to business.name, business %> </h4>
		<h4><%= business["address"] %></h4>
	  <h4><%= business["city"] %></h4>
	  <h4><%= business["state"] %></h4>
	 <% end %>
<% end %> 


<h2>By Employee Count</h2>
	<% @by_employees.each do |business| %>
		<h3><%= link_to business.first.name, business.first %>
		# of employees: <%= business.first.users.uniq.count %> </h3>
		<h4><%= business.first["address"] %></h4>
	  <h4><%= business.first["city"] %></h4>
	  <h4><%= business.first["state"] %></h4>
	<%end%>

app/views/businesses/show.html.erb
<h1> <%= @business.name %></h1>
<h2> <%= @business.address + ", " + @business.city + ", " + @business.state %>, <%= @business.country %> </h2>

<% if current_user %>
	<% current_user.jobs.each do |job|%> 
		<% if job.business_id == @business.id %>

			<h3> Your Position: <%= job.position %> 
			<% if job.user_id == current_user.id %>
				<%= link_to 'Edit Job', edit_job_path(id: job.id) %></h3>
			<% end %>
		<% end %>
	<% end %>


	<div><%= link_to "Add Job", new_job_path(business_id: @business.id) %></div>
	<h3> Latitude: <%= @business.latitude %> </h3>
	<h3> Longitude: <%= @business.longitude %> </h3>
	<h3> <%= @business.phone %> </h3>
	<h3> Category: <%= @business.category %> </h3>
	<h3> Parent Category: <%= @business.parent_category %> </h3>

	<h2> Positions by # of Employees</h2>

	<% @positions.each do |position, total|%>
		<h3> 
		<a href="#<%= position %>-list"><%= position %>s: <%= total %> </a></h3>
	<% end %>
  
	<div class="business-lists">
		<h2> Employees by Name</h2>
		<div class="user-items-container">
			<% @business.users.uniq.each do |user|%>
				<div class="user-item-container">
					<h3> <%= link_to user.name, user_path(id: user.id) %>: 	</h3>
					<% user.jobs.each do |job|%> 
						<% if job.business_id == @business.id %>
				 			<h4> <%= job.position %> 
				 			<% if job.user_id == current_user.id %>
								<%= link_to 'Edit Job', edit_job_path(id: job.id) %> </h4>
							<% end %>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>

	<div class="business-lists">
		<h2> Employees by Position</h2>
		<% @positions.each do |position| %>
			<div class="business-lists">
				<a id="<%=position.first%>-list"> <%= position.first %>s: </a>
					<div class="user-items-container user-by-position">
					<% @business.jobs.each do |job| %>
						<% if job.position == position.first %>
							<div class="user-item-container">
								<h4>
								<%= link_to (User.find(job.user_id)).name, User.find(job.user_id) %> 
								<% if job.user_id == current_user.id %>
								<%= link_to 'Edit Job', edit_job_path(id: job.id) %> 
								<% end %>
								</h4>

							</div>
						<% end %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>


<% else %>
	Please Sign Up
<% end %>