config/routes.rb
Conectup::Application.routes.draw do
 
  get "comments/index"
  get "comments/new"
  devise_for :users
  root :to => "users#show"
  
  resources :users do 
    resources :comments
  end

  resources :businesses do 
    resources :comments
  end

  resources :searches do
    resources :comments
  end

  resources :jobs do 
    resources :comments
  end

  resources :friendships do
    resources :comments
  end

  resources :comments

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :jobs
  has_many :businesses, through: :jobs
  has_many :friendships
  has_many :friends, through: :friendships
  
  # comments for messaging
  has_many :comments, as: :commentable

  validates :name, presence: true
  validates :email, presence: true
  
  def friends_of_friend(the_friend)
    friends_of_friend = []
    self.friends.each do |friend|
      the_friend.friends.each do |friends_friend|
        if friend == friends_friend
          friends_of_friend << friend 
        end
      end
    end
    return friends_of_friend
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

  end

  def show 
    if params[:id] != nil
      @user = User.find(params[:id])
    else
      @user = current_user
    end

    ### LEFT OFF HERE 12AM
    ## try redirecting to comment show page instead of user page for simplicity
    
    # if @user.jobs.each do |job| 
    #   if job.comments != nil
    #   @commentable = Job.find(job.id)
    #   @comments = @commentable.comments
    #   @comment = Comment.new
    # end

    respond_to do |format|
      format.html
      format.json { render json: @job }
    end

  end


end

app/views/users/index.html.erb
<div class="search-users-field">
	<% form_tag users_path, :method => 'get' do %>
	  <p>
	    <%= text_area_tag :search, params[:search] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
	<% end %>
</div>

<%= form_for users_path do |f| %>
	<div>
		<%= f.label :user %>
		<%= f.text_field :business_name, placeholder: "#{current_user.name}'s Diner" %>
	</div>
	<div>
		<%= f.label :city, "City, State" %>
		<%= f.text_field :city, placeholder: "#{current_user.city_state}" %>
	</div>
	<div>
		<%= f.submit "Search" %>
	</div>
<% end %>













<div class="user-items-container">

	<% @users.each do |user|%>
		<div class="user-item-container">
		<h2><%= link_to user.name, user %></h2>
		<h3><%= user.email %></h3>
			<% if user != current_user && user.friends.include?(current_user) == nil %>
				<h3> <%= link_to "Add Friend", friendships_path(friend_id: user.id), method: :post %> </h3>
			<% end %>
			<% if user.friends.include?(current_user) != nil %>
				<h3> <%= link_to "Remove Friend", friendships_path(friend_id: user.id), method: :delete %> </h3>
			<% end %>
		</div>
	<% end %>
</div>

	

app/views/users/show.html.erb
<% if @user %>
	<div class="user-show-header">
		<ul class="user-header-list">
			<li class="user-show-info">
				<h2> <%= @user.name %> </h2>
				<% if (@user == current_user) %>


				<%= image_tag @user.avatar.url %>

					<h3><%= @user.email %> </h3>
					<h3> <%= @user.address %> </h3>
				<% end%>
				<h3> <%= @user.city_state %> </h3>
			</li>

			<li class="user-show-picture">PICTURE GOES HERE</li>
		</ul>
	</div>
<% end %>

<% if current_user && (@user == current_user) %>
	<div class="edit-profile-button">
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
	</div>
<% end %>

<% if current_user %>
	<% if @user != current_user && @user.friends.include?(current_user) == nil %>
		<h3> <%= link_to "Add Friend", friendships_path(friend_id: @user.id), method: :post %> </h3>
	<% end %>

		<% if (@user == current_user) || (@user.friends.include?(current_user)) %>
			<h3>Work Experience:</h3>
			<% if current_user.id == @user.id %>
				<div class="search-fields">
					<%= link_to "Add Work History", new_search_path %>
				</div>
			<% end %>

			<div class="user-items-container">
				<% @user.jobs.each do |job| %>	
					<div class="user-item-container">
						<h4><%= link_to (job.business.name + ": " + job.business.city + ", " + job.business.state), job.business %> </h4>
						<% if current_user.id == @user.id %>
							<h5><%= link_to 'Edit', edit_job_path(job) %></h5>	
						<% end %>	
						<h4> <%= job.position %> </h4>
						<h4> <%= job.start_date.strftime("%m/%d/%Y") %> to <%= job.end_date.strftime("%m/%d/%Y") %></h4>
						<% if @user != current_user %>
						<h4> <%=link_to "Add Reference", new_job_comment_path(job_id: job.id, commentable: @commentable, user_id: @user.id ) %></h4>
						<% end %>
						<h4> <%=link_to "View References", job %></h4>
					</div>
				<% end %>
			</div>


			<div class="friends-list-container">
				<h3>Connections</h3>

					<% if @user == current_user %>
						<%= link_to "Make More Connections", users_path %>
					<% end %>

					<div class="user-items-container">
					<% for friendship in @user.friendships %>
						<div class="user-item-container">
							<%= image_tag friendship.friend.avatar.url(:thumb) %>
							<h4>	<%= link_to friendship.friend.name, friendship.friend %>
							<% if @user == current_user || friendship.friend == current_user %>
								<%= link_to "remove", friendship, method: :delete %></h4>
							<% end %>
							<h4>Mutual Friends: <%= current_user.friends_of_friend(friendship.friend).count %></h4>
							<h3>
								<% current_user.friends_of_friend(friendship.friend).each do |friend|%>
									<%= link_to friend.name, friend%>
								<% end %>
							</h3>
						</div>
					<% end %>
			</div>

		<% end %>

<% else %>
	<div class="row">
		<div class="join-description"><p>
			Connect with other retail and restaurant employees to find great places to work and great people to work with!</p>
		</div>
	</div>
<% end %>