config/routes.rb
Conectup::Application.routes.draw do
 
  get "comments/index"
  get "comments/new"
  devise_for :users
  root :to => "users#show"
  
  resources :users do 
    resources :comments
  end

  resources :businesses do 
    resources :comments
  end

  resources :searches do
    resources :comments
  end

  resources :jobs do 
    resources :comments
  end

  resources :friendships do
    resources :comments
  end

  resources :comments

  

end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :jobs
  has_many :users, through: :jobs
  has_many :search_businesses
  has_many :searches, through: :search_businesses

  # reviews, comments on business
  has_many :comments, as: :commentable

  validates :name, presence: true
  validates :fs_id, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :category, presence: true
  validates :parent_category, presence: true


  def positions_list
    @all_positions = []
    self.jobs.each do |job|
      @all_positions << job.position 
    end
    positions_totals(@all_positions)
  end

  def positions_totals(positions)
    total_positions = {}
    positions.each do |position|
      if total_positions[position] == nil
        total_positions[position] = 1
      else
        total_positions[position] += 1
      end
    end
    return total_positions.sort_by {|position, number| position}
  end

  def self.categories
    @all_categories_list = []
    self.all.each do |business|
      @all_categories_list << business.category
    end
    @uniq_categories = @all_categories_list.uniq!
    self.by_category(@uniq_categories)
  end

  def self.by_category(categories)
    @by_category = {}
    categories.each do |category|
      self.all.each do |business|
        if business.category == category
          if @by_category[category] == nil 
            @by_category[category] = [business]
          else
            @by_category[category] += [business]
          end
        end
      end
    end 
    return @by_category
  end

  def self.by_employee_count
    @by_employees ={}
    self.all.each do |business|
      @by_employees[business] = business.users.count
    end
    return @by_employees.sort_by { |business, employees| employees }
  end



end

app/models/search.rb
class Search < ActiveRecord::Base
  has_many :search_businesses
  has_many :businesses, through: :search_businesses
  
  # tips, comments on a search area?
  has_many :comments, as: :commentable

  validates :business_name, presence: true
  validates :city, presence: true

  def show_businesses
    @businesses ||= populate_businesses
    self.businesses
  end

  # private

  def populate_businesses
    @client = Foursquare2::Client.new(:client_id => ENV["CLIENT_ID"], :client_secret => ENV["CLIENT_SECRET"])
    fs_businesses = @client.search_venues(:near => city, :query => business_name)
    fs_businesses = fs_businesses.first[1].first["items"]
    if fs_businesses == nil
      return false
    else
      fs_businesses.each do |fs_business|
        ## need to change parent category to an array and remove last .first
       business = Business.find_or_create_by(name: fs_business.name, address: fs_business.location.address, city: fs_business.location.city, state: fs_business.location.state, country: fs_business.location.country, latitude: fs_business.location.lat.to_s, longitude: fs_business.location.lng.to_s, phone: fs_business.contact.formattedPhone, category: fs_business.categories.first.name, parent_category: fs_business.categories.first.parents.first, fs_id: fs_business.id)
       self.businesses << business
     end
    end
  end


end 

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def new
    @search = Search.new
  end

  def create
     @search = Search.where(business_name: params[:search]["business_name"].downcase, city: params[:search]["city"].downcase).first
    if !@search.present?
      @search = Search.new(business_name: params[:search]["business_name"].downcase, city: params[:search]["city"].downcase)
      @search.save
      @search.show_businesses
    end
    render :show
  end

  def update
    ## uniquely using update to do new searches, not atually update  a search
    ## same as create method
    @search = Search.where(business_name: params[:search]["business_name"].downcase, city: params[:search]["city"].downcase).first
    if !@search.present?
      @search = Search.new(business_name: params[:search]["business_name"].downcase, city: params[:search]["city"].downcase)
      @search.save
      @search.show_businesses
    end
    render :show
  end

  def show
    @search = Search.find(params[:id])
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for @search do |f| %>
	<div>
		<%= f.label :business_name %>
		<%= f.text_field :business_name, placeholder: "#{current_user.name}'s Diner" %>
	</div>
	<div>
		<%= f.label :city, "City, State" %>
		<%= f.text_field :city, placeholder: "#{current_user.city_state}" %>
	</div>
	<div>
		<%= f.submit "Search" %>
	</div>
<% end %>

app/views/searches/new.html.erb
<%= render "form" %>

app/views/searches/show.html.erb
<%= render "form" %>

<h1>Search Results</h1>

<% if @search.businesses.count < 1 %>
	<h3>No matches</h3>

<% else %>

	<div class="user-items-container">

		<% @search.businesses.each do |business| %>
			<div class="user-item-container">
				<h3><%= link_to (business["name"]), business %> </h3>

				<h5><%= link_to "Add Job", new_job_path(business_id: business.id) %></h5>
				
				<% if current_user %>
					<% if business.user_ids.include?(current_user.id) %>
						<% current_user.jobs.each do |job|%> 
							<% if job.business_id == business.id %>
				
								<h5><%= job.position %> 
								<%= link_to 'Edit Job', edit_job_path(id: job.id) %></h5>

				
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			  <h4><%= business["address"] %></h4>
			  <h4><%= business["city"] %></h4>
			  <h4><%= business["state"] %></h4>

			  <ul class="business-users-list">
			  	<% business.users.uniq.each do |user| %>
			  		<li class="business-user-item">
			  			<%= link_to user.name %>
			  		</li>
			  	<% end %>
			  </ul>
			</div>
		<% end %>
	</div>

<% end %>